# **EDA** (Exploratory Data Analysis)

#### Imports

In [11]:
import pandas as pd

#### Loading Data

In [16]:
def load_data():
    loaded_data = []

    for i in range(7):
        data = pd.read_excel(f"../data/raw/nez-opendata-202{i}.xlsx")

        data.columns = ['accident_id', 'department', 'municipality', 'date_time', 'longitude', 'latitude', 'accident_type', 'involved_vehicles_num', 'description']
        
        # Date and Time parsing
        data['date_time'] = pd.to_datetime(
            data['date_time'],
            format = "%d.%m.%Y,%H:%M",
            errors = "coerce"
        )

        loaded_data.append(data)
    
    return pd.concat(loaded_data, ignore_index=True)

In [17]:
data = load_data()

#### Base Analysis

In [18]:
data.head()

,accident_id,department,municipality,date_time,longitude,latitude,accident_type,involved_vehicles_num,description
0,1278576,BEOGRAD,BARAJEVO,2020-01-07 10:10:00,20.301589,44.568563,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...
1,1278948,BEOGRAD,BARAJEVO,2020-01-09 12:50:00,20.413280,44.579780,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...
2,1278074,BEOGRAD,BARAJEVO,2020-01-10 10:05:00,20.312560,44.575470,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...
3,1278582,BEOGRAD,BARAJEVO,2020-01-10 15:15:00,20.412190,44.637770,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...
4,1278638,BEOGRAD,BARAJEVO,2020-01-16 16:45:00,20.381686,44.633030,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...

In [20]:
data.shape

(205352, 9)

In [21]:
data.dtypes

accident_id                       int64
department                       object
municipality                     object
date_time                datetime64[ns]
longitude                       float64
latitude                        float64
accident_type                    object
involved_vehicles_num            object
description                      object
dtype: object

In [23]:
data.isna().sum()

accident_id              0
department               0
municipality             0
date_time                0
longitude                0
latitude                 0
accident_type            0
involved_vehicles_num    0
description              0
dtype: int64

#### Time Analysis

In [27]:
data['date_time'] = pd.to_datetime(data['date_time'])

data['hour'] = data['date_time'].dt.hour
data['day_of_week'] = data['date_time'].dt.day_of_week
data['month'] = data['date_time'].dt.month
data['year'] = data['date_time'].dt.year

data.head()

,accident_id,department,municipality,date_time,longitude,latitude,accident_type,involved_vehicles_num,description,hour,day_of_week,month,year
0,1278576,BEOGRAD,BARAJEVO,2020-01-07 10:10:00,20.301589,44.568563,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...,10,1,1,2020
1,1278948,BEOGRAD,BARAJEVO,2020-01-09 12:50:00,20.413280,44.579780,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,12,3,1,2020
2,1278074,BEOGRAD,BARAJEVO,2020-01-10 10:05:00,20.312560,44.575470,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,10,4,1,2020
3,1278582,BEOGRAD,BARAJEVO,2020-01-10 15:15:00,20.412190,44.637770,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...,15,4,1,2020
4,1278638,BEOGRAD,BARAJEVO,2020-01-16 16:45:00,20.381686,44.633030,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,16,3,1,2020

#### Geo Analysis

#### Correlations