## **Road Pulse:** Feature Engineering

### Library Imports

In [28]:
import numpy as np
import pandas as pd

### **Loading data**

In [12]:
def load_data():
    loaded_data = []

    for i in range(7):
        data = pd.read_excel(f'../data/raw/nez-opendata-202{i}.xlsx')
        data.columns = ['accident_id', 'department', 'municipality', 'date_time', 'longitude', 'latitude', 'accident_type', 'involved_vehicles_num', 'description']

        data['date_time'] = pd.to_datetime(
            data['date_time'],
            format="%d.%m.%Y,%H:%M", 
            errors='coerce'
        )

        loaded_data.append(data)

    return pd.concat(loaded_data)

In [13]:
data = load_data()

In [14]:
data.head()

,accident_id,department,municipality,date_time,longitude,latitude,accident_type,involved_vehicles_num,description
0,1278576,BEOGRAD,BARAJEVO,2020-01-07 10:10:00,20.301589,44.568563,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...
1,1278948,BEOGRAD,BARAJEVO,2020-01-09 12:50:00,20.413280,44.579780,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...
2,1278074,BEOGRAD,BARAJEVO,2020-01-10 10:05:00,20.312560,44.575470,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...
3,1278582,BEOGRAD,BARAJEVO,2020-01-10 15:15:00,20.412190,44.637770,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...
4,1278638,BEOGRAD,BARAJEVO,2020-01-16 16:45:00,20.381686,44.633030,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...

In [20]:
data.to_excel('../data/raw/nez-opendata-all.xlsx', index=False)

### **Feature Enginnering**

In [25]:
data['year'] = data['date_time'].dt.year
data['month'] = data['date_time'].dt.month
data['day_of_week'] = data['date_time'].dt.day_of_week
data['hour'] = data['date_time'].dt.hour

data = data.drop(columns='date_time')

In [26]:
data.head()

,accident_id,department,municipality,longitude,latitude,accident_type,involved_vehicles_num,description,year,month,day_of_week,hour
0,1278576,BEOGRAD,BARAJEVO,20.301589,44.568563,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...,2020,1,1,10
1,1278948,BEOGRAD,BARAJEVO,20.413280,44.579780,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,12
2,1278074,BEOGRAD,BARAJEVO,20.312560,44.575470,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2020,1,4,10
3,1278582,BEOGRAD,BARAJEVO,20.412190,44.637770,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...,2020,1,4,15
4,1278638,BEOGRAD,BARAJEVO,20.381686,44.633030,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,16

In [30]:
data['day_type'] = np.where((data['day_of_week'] == 5) | (data['day_of_week'] == 6), "Weekend", "Weekday")

In [31]:
data.head()

,accident_id,department,municipality,longitude,latitude,accident_type,involved_vehicles_num,description,year,month,day_of_week,hour,day_type
0,1278576,BEOGRAD,BARAJEVO,20.301589,44.568563,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...,2020,1,1,10,Weekday
1,1278948,BEOGRAD,BARAJEVO,20.413280,44.579780,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,12,Weekday
2,1278074,BEOGRAD,BARAJEVO,20.312560,44.575470,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2020,1,4,10,Weekday
3,1278582,BEOGRAD,BARAJEVO,20.412190,44.637770,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...,2020,1,4,15,Weekday
4,1278638,BEOGRAD,BARAJEVO,20.381686,44.633030,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,16,Weekday

In [34]:
data.drop(columns='accident_id').head()

,department,municipality,longitude,latitude,accident_type,involved_vehicles_num,description,year,month,day_of_week,hour,day_type
0,BEOGRAD,BARAJEVO,20.301589,44.568563,Sa mat.stetom,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...,2020,1,1,10,Weekday
1,BEOGRAD,BARAJEVO,20.413280,44.579780,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,12,Weekday
2,BEOGRAD,BARAJEVO,20.312560,44.575470,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2020,1,4,10,Weekday
3,BEOGRAD,BARAJEVO,20.412190,44.637770,Sa mat.stetom,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...,2020,1,4,15,Weekday
4,BEOGRAD,BARAJEVO,20.381686,44.633030,Sa povredjenim,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,16,Weekday

In [36]:
mapping = {
    'Sa mat.stetom': 'material',
    'Sa povredjenim': 'injured',
    'Sa poginulim': 'dead',
}

In [37]:
data['accident_type'] = data['accident_type'].map(mapping)

In [38]:
data.head()

,accident_id,department,municipality,longitude,latitude,accident_type,involved_vehicles_num,description,year,month,day_of_week,hour,day_type
0,1278576,BEOGRAD,BARAJEVO,20.301589,44.568563,material,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...,2020,1,1,10,Weekday
1,1278948,BEOGRAD,BARAJEVO,20.413280,44.579780,material,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,12,Weekday
2,1278074,BEOGRAD,BARAJEVO,20.312560,44.575470,material,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2020,1,4,10,Weekday
3,1278582,BEOGRAD,BARAJEVO,20.412190,44.637770,material,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...,2020,1,4,15,Weekday
4,1278638,BEOGRAD,BARAJEVO,20.381686,44.633030,injured,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,16,Weekday

In [41]:
data['accident_type'] = np.where((data['accident_type'] == 'Sa mat.stetom') |( data['accident_type'] == 'Sa povredjenim'), 0, 1)

In [42]:
data.head()

,accident_id,department,municipality,longitude,latitude,accident_type,involved_vehicles_num,description,year,month,day_of_week,hour,day_type
0,1278576,BEOGRAD,BARAJEVO,20.301589,44.568563,1,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...,2020,1,1,10,Weekday
1,1278948,BEOGRAD,BARAJEVO,20.413280,44.579780,1,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,12,Weekday
2,1278074,BEOGRAD,BARAJEVO,20.312560,44.575470,1,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2020,1,4,10,Weekday
3,1278582,BEOGRAD,BARAJEVO,20.412190,44.637770,1,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...,2020,1,4,15,Weekday
4,1278638,BEOGRAD,BARAJEVO,20.381686,44.633030,1,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,16,Weekday

In [43]:
data['is_night'] = data['hour'].between(22, 23) | data['hour'].between(0, 6)

In [44]:
data.head()

,accident_id,department,municipality,longitude,latitude,accident_type,involved_vehicles_num,description,year,month,day_of_week,hour,day_type,is_night
0,1278576,BEOGRAD,BARAJEVO,20.301589,44.568563,1,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...,2020,1,1,10,Weekday,False
1,1278948,BEOGRAD,BARAJEVO,20.413280,44.579780,1,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,12,Weekday,False
2,1278074,BEOGRAD,BARAJEVO,20.312560,44.575470,1,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2020,1,4,10,Weekday,False
3,1278582,BEOGRAD,BARAJEVO,20.412190,44.637770,1,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...,2020,1,4,15,Weekday,False
4,1278638,BEOGRAD,BARAJEVO,20.381686,44.633030,1,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,16,Weekday,False

In [45]:
data['is_rush'] = data['hour'].isin([7, 8, 16, 17, 18])

In [46]:
data.head()

,accident_id,department,municipality,longitude,latitude,accident_type,involved_vehicles_num,description,year,month,day_of_week,hour,day_type,is_night,is_rush
0,1278576,BEOGRAD,BARAJEVO,20.301589,44.568563,1,SN SA JEDNIM VOZILOM,Nezgoda sa jednim vozilom – silazak sa kolovoz...,2020,1,1,10,Weekday,False,False
1,1278948,BEOGRAD,BARAJEVO,20.413280,44.579780,1,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,12,Weekday,False,False
2,1278074,BEOGRAD,BARAJEVO,20.312560,44.575470,1,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću istim putem ...,2020,1,4,10,Weekday,False,False
3,1278582,BEOGRAD,BARAJEVO,20.412190,44.637770,1,SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PREL...,Najmanje dva vozila koja se kreću različitim p...,2020,1,4,15,Weekday,False,False
4,1278638,BEOGRAD,BARAJEVO,20.381686,44.633030,1,SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA,Najmanje dva vozila koja se kreću u istom smer...,2020,1,3,16,Weekday,False,True

In [47]:
data['involved_vehicles_num'].unique()

<StringArray>
[                              'SN SA JEDNIM VOZILOM',
          'SN SA NAJMANjE DVA VOZILA – BEZ SKRETANjA',
 'SN SA NAJMANjE DVA VOZILA – SKRETANjE ILI PRELAZAK',
                          'SN SA PARKIRANIM VOZILIMA',
                                     'SN SA PEŠACIMA']
Length: 5, dtype: str

In [ ]:
data.drop(columns='accident_id')

### **Saving preprocessed data**

In [35]:
data.to_excel('../data/processed/processed_accident_data_srb.xlsx', index=False)