# **ML Model:** XGBoost

## **Notes:**

**XGBoost** (*eXtreme Gradient Boosting*) is boosting algorithm. Unlike **RF** (*Random Forest*) which builds trees parallel, boosting builds them sequentially and each of them tries to correct bad decisions of the previous one.

## **Implementation:**

#### Librabry imports

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score

### **Load data**

In [4]:
data = pd.read_excel('../data/processed/accident_processed_srb.xlsx')
data.head(3)

   accident_type  ...  description_encoded
0              0  ...                   24
1              0  ...                   17
2              0  ...                    7

[3 rows x 15 columns]

In [6]:
X = data.drop(columns='accident_type')
y = data['accident_type']

In [7]:
X.head(3)

   municipality_encoded  ...  description_encoded
0                     9  ...                   24
1                     9  ...                   17
2                     9  ...                    7

[3 rows x 14 columns]

In [8]:
y.head(3)

0    0
1    0
2    0
Name: accident_type, dtype: int64

### **Split data**

### **Training**

### **Evaluation**

### **Additional:**